### ISSUE TITLE
add namespace

### ISSUE THREAD

**Issue by hoongun** [cypreess/django-getpaid#15]
Hello
When i'm including a getpaid urls for my project like a namespace and trying to open a success url of some payment backend, i'm getting an error "NoReverseMatch at /getpaid.backends.payu/success/1/" on line:

    return HttpResponseRedirect(reverse('getpaid-success-fallback', kwargs={'pk': self.object.pk}))

Problem will solved if add namespace before url name "getpaid-success-fallback", but it is a bad way. How to solve this problem?

**Comment by pawciobiel** [comment]
Since we already dropped support for django <1.6 it may make sense to add namespace.
It's just IMHO it would be good to add more tests before we do this.

Blocked by #65
