### ISSUE TITLE
Integration with django-plans

### ISSUE THREAD

**Issue by AndrewLvov** [cypreess/django-getpaid#47]
In short:
manuals and sample test project suggest that listener should treat order.total as a property::
def new_payment_query_listener(sender, order=None, payment=None, **kwargs):
    """
    Here we fill only two obligatory fields of payment, and leave signal handler
    """
    payment.amount = order.total
    payment.currency = order.currency
    # ...

However, django-plans implement Order.total as a function::
def total(self):
  # ...

Combining these two projects leads to a problem, for which I see 3 possible solutions:
1. Fix order.total => order.total() everywhere in django-getpaid.
2. Make Order.total in django-plans a property.
3. In every project inherit from plans.models.Order and redefine total as a property.
In this case we have to document it somehow, but I don't really like this option.

**Comment by pawciobiel** [comment]
@AndrewLvov getpaid doesn't care about (tries not to use) order at all. You can define your signal listener the way you want it (django-plans want's it). We can not update documentation for every subscription app that is out there.
I'm sorry but I can not see how this is a problem for you.
