### ISSUE TITLE
Django 1.8 issue

### ISSUE THREAD

**Issue by jarand** [cypreess/django-getpaid#60]
It seems that for now getpaid is not fully compatible with Django 1.8.
When try to makemigrations i've got following error:

File .......\lib\site-packages\getpaid\forms.py", line 6, in <module>
    from django.forms.widgets import HiddenInput, RadioSelect, RadioFieldRenderer, RadioInput
ImportError: cannot import name RadioInput

From version 1.8 Radio Input is removed from django.forms.widgets.
(https://docs.djangoproject.com/en/1.8/releases/1.8/)

Is there any possibility to fix it ?

**Comment by pawciobiel** [comment]
Please install version from github.
https://github.com/cypreess/django-getpaid/blob/master/getpaid/forms.py#L6

**Comment by jarand** [comment]
Many thanks. Everything's working now.
