### ISSUE TITLE
ImportError: No module named celery.task.base

### ISSUE THREAD

**Issue by vikas0713** [cypreess/django-getpaid#69]
after django-getpaid setup and model registering when i tried to run the command makemigrations it throws the error "ImportError: No module named celery.task.base

**Comment by pawciobiel** [comment]
@vikas0713 what versions do you use?

**Comment by vikas0713** [comment]
1.8

**Comment by pawciobiel** [comment]
and celery?

**Comment by vikas0713** [comment]
i have no idea about celery!

**Comment by vikas0713** [comment]
i've installed the celery by using pip install celery,
Now it's giving me the error  "ImportError: cannot import name Payment"

**Comment by vikas0713** [comment]
python 2.7 and mysql db

**Comment by pawciobiel** [comment]
Would you be so kind and past your TB please? :-)

**Comment by pawciobiel** [comment]
no stack trace -> closing.
