### ISSUE TITLE
Using django-getpaid behind proxy

### ISSUE THREAD

**Issue by kriestof** [cypreess/django-getpaid#76]
When using getpaid on server behind proxy(ie. when there is docker with few containers in  app) it currently doesn't get real ip.

For instance in transferuj backend views.py it checks only REMOTE_ADDR, while with proxy it should check HTTP_X_REAL_IP.

Maybe there should be some setting to check if server is behind proxy and then use HTTP_X_REAL_IP? Otherwise one have to disable allowed ip checking which is big security flaw.

**Comment by pawciobiel** [comment]
@kriestof would [this](http://django-getpaid.readthedocs.org/en/latest/backends.html?highlight=Getting%20real%20client%20IP%20address%20from%20HTTP%20request%20meta#payment-backends) be of any help?

**Comment by kriestof** [comment]
@pawciobiel fair enough. Sorry for troubling, I should look at first to the documentation.

**Comment by pawciobiel** [comment]
no worries, we are here to help each other...
