### ISSUE TITLE
Tests are failing on Django 1.8.4, Python 3.4

### ISSUE THREAD

**Issue by glothriel** [cypreess/django-getpaid#78]
![image](https://cloud.githubusercontent.com/assets/4959057/9835698/9da13606-59f8-11e5-862d-1d4418e4115f.png)

**Comment by glothriel** [comment]
'Select a valid choice. getpaid.backends.payu is not one of the available choices.'

**Comment by glothriel** [comment]
After adding getpaid.backends.payu and uncommenting payu backend setting the problem is fixed. Question now is if we should ship backend specific tests in test project itself?

**Comment by pawciobiel** [comment]
Good question. Tests may need a refactoring, see #65
