### ISSUE TITLE
accept_payment task failure in PayU backend

### ISSUE THREAD

**Issue by kriestof** [cypreess/django-getpaid#82]
According to [documentation](https://docs.python.org/3.4/library/urllib.request.html#urllib.request.Request) urllib in python 3.4 requires data be encoded to bytes.

I get the following error when using PayU backend:

```
POST data should be bytes or an iterable of bytes. It cannot be of type str.
```

```
Stacktrace (most recent call last):

  File "celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "getpaid/backends/payu/tasks.py", line 19, in get_payment_status_task
    processor.get_payment_status(session_id)
  File "getpaid/backends/payu/__init__.py", line 182, in get_payment_status
    response = urlopen(request)
  File "urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "urllib/request.py", line 461, in open
    req = meth(req)
  File "urllib/request.py", line 1112, in do_request_
    raise TypeError(msg)
```

**Comment by kriestof** [comment]
I consider if it's not connected with #57. Changing urllib to requests probably would fix problem.

**Comment by pawciobiel** [comment]
@kriestof what version of python, django, getpaid, celery (and django-celery) do you use?

**Comment by pawciobiel** [comment]
@kriestof can you try 1.7.3 and let me know if this works for you?

**Comment by kriestof** [comment]
I can but if you don't mind I will do it in the next week.

**Comment by pawciobiel** [comment]
no probs, I think I fixed this, if not please reopen.

**Comment by kriestof** [comment]
@pawciobiel It did the job, thank you!
