### ISSUE TITLE
DotPay returns an error on default settings

### ISSUE THREAD

**Issue by pawelad** [cypreess/django-getpaid#83]
Hi,
When using your package, DotPay returns an error when redirected from the site. The error disappears when URLs are removed from the link.

Could you point me in the direction when the string are encode? I figure it's somewhere in `get_gateway_url` but I can't quite find it.

**Comment by pawelad** [comment]
My bad, the reason it was showing an error was insecure connection on `URLC` parameter.

Sorry for the bother

**Comment by pawciobiel** [comment]
no worries dude
