### ISSUE TITLE
Succesfull DotPay transaction doesn't change order status

### ISSUE THREAD

**Issue by pawelad** [cypreess/django-getpaid#89]
Hi,

I'm having problems with getting the succesfull signal back from DotPay transaction and I was wondering if anyone could help me debug it.
Everything works well on `dummy` buckend, but after switching to `dotpay` I can't get the order status changed from `in progress` to `paid`. Everything else works good, it returns to order page, but it doesn't receive the signal and doesn't change the status. I've tried debugging it a couple of ways now but no luck.

Thanks in advance

**Comment by pawciobiel** [comment]
@pawelad what's your python, django, getpaid version and what's your logging configuration in django settings?

**Comment by pawelad** [comment]
Python 3.4, Django 1.8, GetPaid from installed via pip from GitHub (the version on PyPI didn't allow for custom `gateway_url`).
I tried configuring logging, but it's not producing anything: http://pastebin.com/0SX4BX2U

Like I said, `dummy` backend worked well, but I can only test `DotPay` on production because their `URLC` parameter doesn't work with localhost (or at least I couldn't manage to get it working).

The thing is, I don't have access to the DotPay account, only their ID for the link. And everything seems to work well, it redirects good after the payment and everything, except for the back signal.

**Comment by pawelad** [comment]
OK, I managed to get the logger to output something, but it only print `django.db.backends` stuff.
http://pastebin.com/cFgzuLEr

**Comment by pawciobiel** [comment]
@pawelad can u try something along those lines please:
```
    'handlers': {
        'console' : {
            'level':'DEBUG',
            'class':'logging.StreamHandler',

        },
    },
```

```
'loggers': {
        'getpaid':{
            'handlers': ['console'],
            'level': 'DEBUG',
        }
...
```

**Comment by pawciobiel** [comment]
@pawelad this is just a guess but can you check that your ID is correct and you have generated correct md5 signature?

**Comment by pawelad** [comment]
I changed the logging setting and all I'm getting are Django warnings.

My ID is correct, but I'm not using the md5 signature - that may by it, but from I see it's not listed as required in the [documentation](https://drive.google.com/file/d/0B3e8d_i0AnLFSHdmenU2aWVwODQ/view)

And I just got nginx logs and `getpaid.backends.dotpay/online/` is never accessed.

**Comment by pawelad** [comment]
Do you have any more ideas? I have no idea what to try next.

**Comment by pawciobiel** [comment]
@pawelad 
* fix your logging so you can see debug from `getpaid`
* make sure you have correct domain in your django Sites

**Comment by pawelad** [comment]
@pawciobiel sorry for the such a big delay

Yes, `SITE_ID` is configured corectlly.

And I finally got the logging to work, I think, because I got the message:  
`Got message from not allowed IP ('195.150.9.37',)`

Which is weird because: https://github.com/cypreess/django-getpaid/blob/9573a50ef84875a1458f2f0aaa211b9dc1c06ae9/getpaid/backends/dotpay/__init__.py#L32

**Comment by pawelad** [comment]
OK, so the main problem was with the Nginx configuration, which changed `REMOTE_ADDR` to `127.0.0.1`...
After I found that, the rest was easy.

Thanks for the help!

**Comment by pawciobiel** [comment]
no probs
