### ISSUE TITLE
DotPay backend PIN option

### ISSUE THREAD

**Issue by pawelad** [cypreess/django-getpaid#94]
Hi,

After my problems (#89) with configuration of `DotPay` backend, I think I found a bug, or at least a inaccuracy.

From what I can tell from the DotPay technical manual, the PIN/signature/MD5 check option isn't required, but is always checked by `getpaid` ([link](https://github.com/cypreess/django-getpaid/blob/master/getpaid/backends/dotpay/__init__.py#L53)).
Maybe we should skip it when no PIN is passed to backend options?

And if you want to make it a requirement (DotPay says: `Please mind that lack of parameter md5 on the customer’s system’s site is dangerous and exposes him to financial loss.` so forcing it isn't that bad) then I think it should be noted in the [documentation](https://django-getpaid.readthedocs.org/en/latest/backends.html#dotpay-eu-backend-getpaid-backends-dotpay) and added as a `Required key`.

After response from the dev I could do the appropriate changes and create a PR.

**Comment by pawciobiel** [comment]
@pawelad Do you know if `DotPay` pass `md5` param in the request even if you not configure "PIN" on DotPay side?

**Comment by pawelad** [comment]
It always went into the `if md5`, so I'm guessing yes.

**Comment by pawciobiel** [comment]
So IMO if `md5` param is always present we shouldn't skip this.

**Comment by pawelad** [comment]
So then in my opinion the documentation should state more obviously that `PIN` is in fact required.

**Comment by pawciobiel** [comment]
@pawelad fair enough, I think I can accept a patch/PR for documentation. ;-)

**Comment by pawelad** [comment]
OK, I'll try to do that on the weekend.

**Comment by pawelad** [comment]
Sorry it took so long - completely forgot about it.

**Comment by pawciobiel** [comment]
fixed in #99
